### ISSUE TITLE
Customer POST `me/login` body is void. Should have at least 4 parameters.

### ISSUE THREAD

**Issue by sergy-gzh** [commercetools/commercetools-sdk-typescript#102]
According to documentation 4 params can be passed in the body:
- email
- password
- activeCartSignInMode
- updateProductData

https://docs.commercetools.com/api/projects/me-profile#authenticate-customer-sign-in

instead all arguments are marked as `void` here
https://github.com/commercetools/commercetools-sdk-typescript/blob/70f4267958268c3a6f592c8cd10190e7acf91316/packages/platform-sdk/src/generated/client/login/by-project-key-me-login-request-builder.ts#L28

**Comment by jenschude** [comment]
Fixed by https://github.com/commercetools/commercetools-sdk-typescript/pull/114

Thanks for the report
