### ISSUE TITLE
Runtime error using client-sdk-v2

### ISSUE THREAD

**Issue by samcackett** [commercetools/commercetools-sdk-typescript#126]
So the latest release fixed the webpack issue... but now there's a new issue with missing dependencies. 

We've worked around this now by adding the dependencies manually but we get an error if we don't add them in:
```
{
    "errorType": "ReferenceError",
    "errorMessage": "regeneratorRuntime is not defined",
    "stack": [
        "ReferenceError: regeneratorRuntime is not defined",
        "    at _executeRequest (/var/task/triggerUpcomingReminders.js:54043:53)",
        "    at executeRequest (/var/task/triggerUpcomingReminders.js:54039:26)",
        "    at authMiddlewareBase (/var/task/triggerUpcomingReminders.js:54225:3)",
        "    at /var/task/triggerUpcomingReminders.js:54314:7",
        "    at /var/task/triggerUpcomingReminders.js:53784:9",
        "    at new Promise (<anonymous>)",
        "    at ApiRequest.execute [as requestExecutor] (/var/task/triggerUpcomingReminders.js:53766:14)",
        "    at ApiRequest.execute (/var/task/triggerUpcomingReminders.js:43786:19)",
        "    at getUserEmail (/var/task/triggerUpcomingReminders.js:132338:14)",
        "    at triggerUpcomingReminders (/var/task/triggerUpcomingReminders.js:132642:25)"
    ]
}
```

Adding those dependencies manually to where we construct the commercetools client fixes the issue. i.e. add the dependencies to the package.json
```
    "core-js": "^3.18.1",
    "regenerator-runtime": "^0.13.9",
```

And import them
```
import 'core-js/stable'
import 'regenerator-runtime/runtime'
```

and the runtime error goes away.

We're using these versions of the commercetools SDK's:
```
    "@commercetools/platform-sdk": "^1.18.1",
    "@commercetools/sdk-client-v2": "^0.1.2",
```

in a node 14 environment running on AWS Lambda. We use webpack to package up our code (v5.56.0).

If you need any further info please reply on here.

Thanks,

Sam

**Comment by ajimae** [comment]
Hello Sam,

You can use the zero dependency (umd) build of the `sdk-client-v2` and `platform-sdk` SDK packages, I believe this will fix the issues.

```html
<script src="https://unpkg.com/@commercetools/sdk-client-v2@0.1.2/dist/commercetools-sdk-client-v2.umd.js"></script>
<script src="https://unpkg.com/@commercetools/platform-sdk@1.19.0/dist/commercetools-platform-sdk.umd.js"></script>
```

Or you can force the script to always use the latest version by using the snippets below.

```html
<script src="https://unpkg.com/@commercetools/sdk-client-v2@latest/dist/commercetools-sdk-client-v2.umd.js"></script>
<script src="https://unpkg.com/@commercetools/platform-sdk@latest/dist/commercetools-platform-sdk.umd.js"></script>

```
Please let us know if this works for you.


Regards

**Comment by samcackett** [comment]
Hi @ajimae thanks for getting back to me. 

Please note that this is a NodeJS environment, not a web page and we are pulling packages via npm. On npm I can only see one package https://www.npmjs.com/package/@commercetools/sdk-client-v2 and this package is missing the dependencies I listed above. 

From looking at your source code it looks like it's a transient dependency of Babel which you've accidentally [included](https://github.com/commercetools/commercetools-sdk-typescript/blob/master/package.json) into the build. Things like Babel, Jest etc there's a few in there that should be `devDependencies`.

Could you please assess your package.json and not include dev dependencies in the build and issue a new release?

Alternatively if this package isn't supposed to be used yet, could you let me know? It's linked from the your documentation but I see the version number is 0.x.x which suggests this is in alpha and not ready for production? If so please let me know and update your docs to point to the old one.

Thanks

**Comment by jenschude** [comment]
Yes we in fact used the 0.x.x version as it may not be production ready. It's a port of the node SDK client to typescript. The node SDK client is a dependency of the platform sdk and also be available.

See also here: 

https://github.com/commercetools/commercetools-sdk-typescript/blob/master/packages/platform-sdk/package.json#L26

https://github.com/commercetools/commercetools-sdk-typescript/tree/master/packages/platform-sdk#usage-example

**Comment by samcackett** [comment]
I should add with the dependency added this client is working fine, but I'm happy to move back to the other one if that's what we should do
