### ISSUE TITLE
Some elaboration on how to use the various auth middlewares in a SPA setup?

### ISSUE THREAD

**Issue by asgerjensen** [commercetools/commercetools-sdk-typescript#139]
I'm trying to figure out how and which auth-middlewares i'm supposed to use for an SPA.

at the start of the page load, i create a client with `withClientCredentialsFlow` set to the tokens i got from the merchant center.

Then, when someone adds something to cart, i replace the client, with one using `.withAnonymousSessionFlow`

This works fine, and i can place orders.

I can also register/signup the anonymous user, and even call login, but i dont see it fetching a new token, so i figure i have to do something myself to make that happen, so i tried switching to a new client using the `.withPasswordFlow` middleware, but this has some expectation that the clientId and clientSecret from the Merchant Center is set in the `process.env`, which doesn't exist in the browser.

And, frankly, i'm not even sure thats what i'm supposed to do, as i also see there is something called `.withRefreshTokenFlow`.

The `.login` succeeds, but i dont get any new tokens back (i thought they might be in the response header).

My expectation was probably, that i would instantiate the client ONCE, at application start, and it would monitor the various calls that can lead to token-change, and deal with everything itself, but that doesn't seem to be the case.

For now, i have worked around it, by adding a polyfill to angular, like
```
(window as any).process = {
    env: {}
};
```
and then where i switch to the withPasswordFlow, i'm then setting `process.env.clientId` and `process.env.clientSecret` to the values from Merchant Center.

Unsure, if it is a bug in the v2 client, or not.

```

  public switchToRegisteredCustomer(username: string, password: string) {
     /// HAXXORS 
    process.env.clientId = this.config.clientId;
    process.env.clientSecret = this.config.clientSecret;
    
    let ctpClient: Client = new ClientBuilder()
      .withProjectKey(this.config.projectKey) // not necessary if the projectKey was already passed in the authMiddlewareOptions
      .withPasswordFlow({
        host: this.config.authUrl,
        projectKey: this.config.projectKey,
        credentials: {
          clientId: this.config.clientId,
          clientSecret: this.config.clientSecret,
          user: {
            username,
            password
          }
        },

      })
      .withHttpMiddleware(this.httpMiddlewareOptions)
      .withLoggerMiddleware()
      .build()

    this.client = createApiBuilderFromCtpClient(ctpClient);
  }
```

**Comment by asgerjensen** [comment]
Note: i DID try to see how the Sunrise SPA did it, but it does not seem to use any of the prebuilt client stuff, and rather does its own state machine fiddling based on the `TokenProvider` and its events.

**Comment by ajimae** [comment]
Hi asgerjesen,

The both implementations are correct and are both recommended way to authenticate, it comes down to which you prefer.

The basic difference amongst the two is that, the `ClientBuilder` method doesn't allow you to directly interact with the returned token as the SDK already takes care of this. All you need do is to find a way to switch out the client, depending if it's anonymous or password authenticated user. You can see how this was done [here](https://github.com/commercetools/commercetools-sdk-typescript/blob/master/examples/me/server/src/client/Client.ts)

For the `TokenProvider` method, here you have the choice to retrieve and save the token on the client. The `withRefreshTokenFlow` method generates a new token and replaces the old token with the newly generated one.

Let me know if you still need further clarification or explanation, I will be glad to help.

Regards
