### ISSUE TITLE
OrderLineItemRemoved missing from SNS Messages

### ISSUE THREAD

**Issue by MRVDH** [commercetools/commercetools-sdk-typescript#142]
These are the docs for the message, but it seems that it hasn't been added to the TypeScript package yet: https://docs.commercetools.com/api/message-types#orderlineitemremoved

![image](https://user-images.githubusercontent.com/6686385/141792202-3d001fd7-e8dc-49b8-8c0a-0aabc8723606.png)

**Comment by MRVDH** [comment]
Any explanation as to why this won't be fixed would be appreciated 😄

**Comment by jenschude** [comment]
Good old bots. :)

It's already published in 1.20.0

**Comment by MRVDH** [comment]
Thanks @jenschude! 😄
