### ISSUE TITLE
issue with host and authUrl in sdk-client-v2 docs example 

### ISSUE THREAD

**Issue by briantomkins** [commercetools/commercetools-sdk-typescript#170]
The example client config here:
https://github.com/commercetools/commercetools-sdk-typescript/tree/master/packages/sdk-client

**Current:**
const authMiddlewareOptions = {
  host: 'https://auth.europe-west1.gcp.commercetools.com',
  projectKey,
  credentials: {
    clientId: 'mc-client-id',
    clientSecret: 'mc-client-secrets',
  },
  oauthUri: 'https://auth.europe-west1.gcp.commercetools.com',
  scopes: [`manage_project:${projectKey}`],
  fetch,
}

When both host and oauthUri are supplied the client does not work:
==Error===
FetchError: request to https://auth.vw.eu-central-1.aws.commercetools.comhttps//auth.vw.eu-central-1.aws.commercetools.com failed

SUPPORT-15049

**Comment by ajimae** [comment]
Hi @briantomkins 

This issue has been fixed [here](https://github.com/commercetools/commercetools-sdk-typescript/pull/172).

Please see the updated documentation.

Thanks
