### ISSUE TITLE
/me/password/reset is missing post body

### ISSUE THREAD

**Issue by se1by** [commercetools/commercetools-sdk-typescript#200]
As the title says, there should be a mandatory `CustomerResetPassword` body for the reset endpoint (see [docs](https://docs.commercetools.com/api/projects/me-profile#reset-customers-password)):

https://github.com/commercetools/commercetools-sdk-typescript/blob/c93148cbe222ba89d0aca5ceb113de208015c0e0/packages/platform-sdk/src/generated/client/reset/by-project-key-me-password-reset-request-builder.ts#L20-L25

Otherwise you can't provide the needed fields and the request will fail.

**Comment by jenschude** [comment]
Thanks for the report.

PR with fix opened in upstream repository
