### ISSUE TITLE
Types import issue

### ISSUE THREAD

**Issue by fishme** [commercetools/commercetools-sdk-typescript#222]
looks like that the typescript package will be wrong generated.
in https://github.com/commercetools/commercetools-sdk-typescript/tree/master/examples/me/server

```@commercetools/sdk-client-v2/src/types/sdk``` is not working only via dist folder.

not clean variant: ```@commercetools/sdk-client-v2/dist/declarations/src```

If it is possible, I guess it makes sense to change the path into ```@commercetools/sdk-client-v2/types```

**Comment by fishme** [comment]
ok, so means to run the examples it needs to change it? or needs to execute something before?

[examples/me/server/src/utils/auth/auth.ts](https://github.com/commercetools/commercetools-sdk-typescript/blob/master/examples/me/server/src/utils/auth/auth.ts)
[examples/me/server/src/utils/auth/tokenProvider.ts](https://github.com/commercetools/commercetools-sdk-typescript/blob/master/examples/me/server/src/utils/auth/tokenProvider.ts)

**Comment by ajimae** [comment]
> ok, so means to run the examples it needs to change it? or needs to execute something before?
> 
> [examples/me/server/src/utils/auth/auth.ts](https://github.com/commercetools/commercetools-sdk-typescript/blob/master/examples/me/server/src/utils/auth/auth.ts) [examples/me/server/src/utils/auth/tokenProvider.ts](https://github.com/commercetools/commercetools-sdk-typescript/blob/master/examples/me/server/src/utils/auth/tokenProvider.ts)

You don't need to work with those file. All you need to do is follow the instruction in the [README.md](https://github.com/commercetools/commercetools-sdk-typescript/blob/master/examples/me) file to run the example application.

Cheers 🥂

**Comment by fishme** [comment]
Well that is the point it runs into an issue like described. However, works for me after the change.

**Comment by jenschude** [comment]
I just tried it and could reproduce your issue when working with a clean repository. When running `yarn install` in the repository root the described issue is gone.

**Comment by ajimae** [comment]
@jenschude This happens because the repository is a monorepo, if you try importing a package which is part of the monorepo, it will want to use the local version instead of pulling it from npm.

**Comment by ajimae** [comment]
This error should now be fixed.
