### ISSUE TITLE
do you have best practices or example to extend generated ApiRoot/client to add additional generic utility functionality ?

### ISSUE THREAD

**Issue by ahmetoz** [commercetools/commercetools-sdk-typescript#229]
We have a pattern for the generic functionality that is extending the client of the nodejs sdk client v1, but could not figure out well the practice in the new ctpClient created by the sdk client v2, do you have an example ?

example for the generic client utility, see: [fetchPagesGraphQl](https://github.com/commercetools/commercetools-cli-scripts/blob/master/utils/client.js#L104-L140)

**Comment by ahmetoz** [comment]
Hey @jenschude @ajimae 
Do you have any suggestions for the use case above ?

**Comment by ajimae** [comment]
I think [this](https://github.com/commercetools/commercetools-sdk-typescript/pull/220) is what you are looking for.

Also kindly look at this [issue](https://github.com/commercetools/commercetools-sdk-typescript/issues/217), to see if related to what you want.
