### ISSUE TITLE
Add httpMiddlewareOptions  missing JS/TS documentation.

### ISSUE THREAD

**Issue by ajimae** [commercetools/commercetools-sdk-typescript#245]
Include documentation to cover for middleware options e.g the `httpMiddlewareOptions` etc

- [x] @ajimae to create an issue in docs repo and link here.
- [x] Docs team create a PR with httpMiddlewareOptions 
- [x] review the PR.

**Comment by ashishhk** [comment]
https://github.com/commercetools/commercetools-docs/pull/2017
