### ISSUE TITLE
code sample /examples/me/server is hard-coded for EU auth and api endpoints

### ISSUE THREAD

**Issue by chrisboyke** [commercetools/commercetools-sdk-typescript#262]
in /examples/me/server/src/utils/options.ts, lines 20, 34, and 50, the URLs are hard-coded, should come from process.env.

**Comment by ajimae** [comment]
Thanks @chrisboyke for pointing this out.

I will effect the necessary changes ASAP.

Thanks

**Comment by ajimae** [comment]
This is done, see [this](https://github.com/commercetools/commercetools-sdk-typescript/pull/263)
