### ISSUE TITLE
Add support for standalone prices endpoint

### ISSUE THREAD

**Issue by lojzatran** [commercetools/commercetools-sdk-typescript#264]
I would like to test the standalone prices using the sdk, but I do not see a support yet. Can you confirm if it's supported or add the feature to the SDK?
https://docs.commercetools.com/api/projects/standalone-prices

**Comment by jenschude** [comment]
Will be part of the next release. Please see https://github.com/commercetools/commercetools-sdk-typescript/pull/258/files
