### ISSUE TITLE
Retry mechanism not retrying on Network Error's   

### ISSUE THREAD

**Issue by Arditc** [commercetools/commercetools-sdk-typescript#271]
Hi,

I hope you are well. We are using the platform-sdk to make requests to the graphql search endpoint. This is running with the AWS Lambda environment. We have seen that the retry mechanism does not capture all network errors.

Library version being used:
 "@commercetools/platform-sdk": "2.6.0"

httpMiddlewareOptions
```   
      const httpMiddlewareOptions: HttpMiddlewareOptions = {
      host: apiHostname,
      fetch,
      enableRetry: true,
      includeResponseHeaders: true,
      timeout: Number(6_000),
      retryConfig: { maxRetries: Number(3) },
      getAbortController: () => new AbortController()
    };
```

Here is an example error log that we saw on the service:
![Screenshot 2022-06-02 at 16 11 55](https://user-images.githubusercontent.com/5559771/171663283-5a105c0b-1570-4772-b5cb-14800a443b62.png)

Telemetry logs to show that the request errored with: "The user aborted a request."
![Screenshot 2022-06-02 at 16 21 46](https://user-images.githubusercontent.com/5559771/171663811-c514a0b2-bde5-44d6-9355-3dc2ca26c81c.png)

Is there a reason why it's not being retried?

Many thanks

**Comment by ajimae** [comment]
Feel free to reopen this issue if the issue is not yet resolved.

Thanks
