### ISSUE TITLE
missing customObjects().withId() function

### ISSUE THREAD

**Issue by Eomm** [commercetools/commercetools-sdk-typescript#276]
Hi,
the client version

```
    "@commercetools/platform-sdk": "2.7.0",
    "@commercetools/sdk-client-v2": "1.4.0",
```

throws an error for this code:

```js
const customObject = (await apiRoot
    .customObjects()
    .withId({ ID: 'uuid-cut' })
    .get()
    .execute()).body
  console.log({ customObject })
```

```
(node:17049) UnhandledPromiseRejectionWarning: TypeError: apiRoot.customObjects(...).withId is not a function
```

Meanwhile, this works as expected:

```
  const customObject = (await apiRoot
    .customObjects()
    .get({ queryArgs: { where: 'id = "uuid-cut"' } })
    .execute()).body
  console.log({ customObject })
  console.log(JSON.stringify(customObject, null, 2))
```

I think it should work as the other CT's components (`products().withId()` etc..)

**Comment by jenschude** [comment]
Cause the endpoint to retrieve a custom object has been deprecated. Please see:

https://docs.commercetools.com/api/releases/2020-09-16-query-custom-objects-in-container

**Comment by Eomm** [comment]
It is not clear to me which is the new API.

I have a CT event that container the path `product.masterData.staged.masterVariant.attributes`.
In those attributes I have a custom object:

```
          {
            "name": "my-custom-obj",
            "value": {
              "typeId": "key-value-document",
              "id": "uuid-cut"
            }
          },
```

How should I get the `my-custom-obj` information?

**Comment by jenschude** [comment]
Could you open a support ticket regarding this issue please as it's not directly an issue of the SDK but that the event may lack information or that there should be an option to retrieve the custom object by ID again
