### ISSUE TITLE
The baseUri value on the request log is handling the default value.

### ISSUE THREAD

**Issue by fiquarato** [commercetools/commercetools-sdk-typescript#277]
Hi,

Looking into the logs of my middleware API, I found that the logs for the request to commercetools the value for the `baseUri` are showing always the default value.

Steps to reproduce: 
1. Follow the Readme to create the ClientBuilder and execute requests. https://github.com/commercetools/commercetools-sdk-typescript/blob/master/packages/platform-sdk/README.md
2. Use a different region (don’t use the default region that is `europe-west1.gcp`.
3. Add `withLoggerMiddleware()` to log the incoming requests and response objects.
4. Execute a request and validate the logs. 

Result log:

`Request:  {
  baseUri: 'https://api.europe-west1.gcp.commercetools.com',
  method: 'GET',
  uriTemplate: '/{projectKey}/carts',
  pathVariables: { projectKey: 'my-project-key' },
  headers: {
    Authorization: 'Bearer my-token,
    'User-Agent': 'commercetools-sdk-javascript-v2/1.4.0 node.js/16.13.1'
  },
  queryParams: undefined,
  uri: '/my-project-key/carts'
}` 

As you can see, the request log is always showing the default baseUri:
`baseUri: 'https://api.europe-west1.gcp.commercetools.com'`

But the request is executed correctly in the `host` defined in the `authMiddlewareOptions`.

Dependencies version: 
`"@commercetools/platform-sdk": "^2.8.0"`
`"@commercetools/sdk-client-v2": "^1.4.0"`

Thanks!!

**Comment by ajimae** [comment]
Hi @fiquarato 

To use a `baseUri` other than the default `'https://api.europe-west1.gcp.commercetools.com` you need to pass it as a second argument to the `createApiBuilderFromCtpClient()` function.

Example
```ts
const {
  ClientBuilder
} = require('@commercetools/sdk-client-v2')
const { createApiBuilderFromCtpClient } = require('@commercetools/platform-sdk')
const fetch = require('node-fetch')

const projectKey = process.env.CTP_PROJECT_KEY
const authMiddlewareOptions = {
  host: "https://auth.us-central1.gcp.commercetools.com",
  projectKey,
  credentials: {
    clientId: process.env.CTP_US_CLIENT_ID
    clientSecret: process.env.CTP_US_CLIENT_SECRET
  },
  scopes: [`manage_project:${projectKey}`],
  fetch,
}

const httpMiddlewareOptions = {
  host: 'https://api.us-central1.gcp.commercetools.com',
  fetch
}

const apiRoot = createApiBuilderFromCtpClient(client, 'https://api.us-central1.gcp.commercetools.com') // this will force the apiRoot to use the provided baseUri
...
```

I hope this helps.

**Comment by fiquarato** [comment]
Hi @ajimae, 

Yep, it helps to get the log with the URL that we are using.

But, this second argument is optional, and I think we should handle the URL set on the client.

Let me know what you think about it! Thanks!

**Comment by ajimae** [comment]
Hi @fiquarato 

Thanks for the feedback, I will have a discussion with my team on this.

Thanks

**Comment by Fedeorlandau** [comment]
Hello there, I was going crazy about this issue as well.

Even if I set the API URL on the middleware the client doesn't seem to care about the API URL at all. If I do it like you propose (second argument) it works just fine.

Thanks for your help.

**Comment by franquarato** [comment]
Hi @ajimae

I'd like to reopen this ticket, as I still see that this issue is occurring. I believe you should make the necessary changes to log the correct URL, as the current behavior causes confusion.
