### ISSUE TITLE
me example has outdated README.md concerning setting up .env

### ISSUE THREAD

**Issue by JohnMarsden24** [commercetools/commercetools-sdk-typescript#285]
In the [me example README](https://github.com/commercetools/commercetools-sdk-typescript/tree/master/examples/me) the setup tells you to create two `.env` files with the `.env` for `/server` being:

```bash
PORT=8085
CTP_CLIENT_ID={clientID}
CTP_PROJECT_KEY={projectKey}
CTP_CLIENT_SECRET={clientSecret}
DEFAULT_CURRENCY=EUR
```

The values that are used to create the middleware options were originally hardcoded and then changed to be loaded from `.env` in [this issue](https://github.com/commercetools/commercetools-sdk-typescript/issues/262), however the README doesn't reflect this change. The above snippet should be:

```bash
PORT=8085
CTP_CLIENT_ID={clientID}
CTP_PROJECT_KEY={projectKey}
CTP_CLIENT_SECRET={clientSecret}
CTP_AUTH_URL={authUrl}
CTP_HOST_URL={hostUrl}
DEFAULT_CURRENCY=EUR
```

As it currently stands if you run this example without adding those to your `.env` you'll get the error of `Missing required option (host)`.

EDIT:

[Your Github action for adding issues is failing](https://github.com/commercetools/commercetools-sdk-typescript/actions/workflows/add_issues_to_project.yml)

**Comment by ajimae** [comment]
Thanks @JohnMarsden24 for pointing this out.

We will update the `README.md` file ASAP.
