### ISSUE TITLE
Add query expansion for active-cart endpoint.

### ISSUE THREAD

**Issue by ajimae** [commercetools/commercetools-sdk-typescript#307]
#### Summary
This issue is related to this ticket
https://jira.commercetools.com/browse/SUPPORT-17334

#### Background
The customer is requesting we add the expansion feature present in the `me/carts` endpoint to the me/active-carts endpoint.

They want to be able to expand a query based on paymentInfo.

Example

```ts
async function getActiveCart() {
  return apiRoot
    .withProjectKey({ projectKey })
    .me()
    .active-cart()
    .get({
      queryArgs: {
        paymentInfo: "*",
        ...
      }
    })
    .execute()
}
```

**Comment by ashishhk** [comment]
This issue was discussed and prioritised, we will pick it up in next few weeks.

**Comment by ajimae** [comment]
This is done and released https://github.com/commercetools/commercetools-sdk-typescript/pull/313
