### ISSUE TITLE
ReferenceTypeId was not updated with "standalone-price"

### ISSUE THREAD

**Issue by cq-fpietron** [commercetools/commercetools-sdk-typescript#312]
Greetings,

[`ReferenceTypeId` union in common.ts](https://github.com/commercetools/commercetools-sdk-typescript/blob/master/packages/platform-sdk/src/generated/models/common.ts#L932) has not been updated to include `standalone-price`. 

This causes TypeScript errors when trying to use `ReferenceTypeId` alongside `Reference`, which includes `StandalonePrice`:

```ts
Type '"standalone-price"' is not assignable to type 'ReferenceTypeId'.
```

It would be great if you patched this, seems like an easy fix (especially since it's in generated code?)

**Comment by ajimae** [comment]
This should be done [PR](https://github.com/commercetools/commercetools-docs/pull/2306)
