### ISSUE TITLE
Way to retrieve auth tokens?

### ISSUE THREAD

**Issue by JohnMarsden24** [commercetools/commercetools-sdk-typescript#314]
In the previous package `@commercetools/sdk-auth` you had the function [`anonymousFlow`](https://commercetools.github.io/nodejs/sdk/api/sdkAuth.html#anonymous-session-flow) which would return you the tokens for an anonymous session. I'm trying to do the same in this package but I'm unable to find a workaround. Looking into a source code the `withAnonymousSessionFlow` middleware retrieves the tokens but [stores them in memory](https://github.com/commercetools/commercetools-sdk-typescript/blob/master/packages/sdk-client/src/sdk-middleware-auth/base-auth-flow.ts#L69) and where I can't get to them. Any ideas or plans to implement this?

EDIT:

I tried to use `execute` straight on the client however the logic it uses [stringifies the body](https://github.com/commercetools/commercetools-sdk-typescript/blob/7512c3f1f488645da3952f296d4f4fe3149b7fba/packages/sdk-client/src/sdk-middleware-http/http.ts#L130) and the `/token` endpoint requires it to be of content `application/x-www-form-urlencoded` so this won't work:

```javascript
const anonClient = new ClientBuilder()
  .withHttpMiddleware({
    host: AUTH_URL,
  })
  .build();

anonClient
  .execute({
    method: 'POST',
    uri: `/oauth/${PROJECT_KEY}/anonymous/token`,
    body: querystring.stringify({
      grant_type: 'client_credentials',
      scopes: [`create_anonymous_token:${PROJECT_KEY}`],
    }),
    headers: {
      'Content-Type': 'application/x-www-form-urlencoded',
      'content-type': 'application/x-www-form-urlencoded',
      Authorization: 'Basic <BASIC AUTH>',
    },
  })
  .then((res) => console.log(res))
  .catch((err) => console.log(err));
```

**Comment by ajimae** [comment]
Hi @JohnMarsden24,

For now, we don't allow the access of the auth token outside of the SDK for security reasons.

Also, you can still use the `@commercetools/sdk-auth` and in the `TypeScript SDK` and it should work as expected. Maybe you can share how you have been trying to use it.


Thanks

**Comment by ThomasLarge** [comment]
Hey @ajimae, just picking up from this. We use the sdk-auth to pass the access token onto the GraphQL client. Here is the example code:

```ts

const { access_token } = await authClient.clientCredentialsFlow();

  const graphQLClient = new GraphQLClient(process.env.GRAPHQL_ENDPOINT, {
    headers: {
      authorization: `Bearer ${access_token}`,
    },
  });

```

Is there a better way to do with with typescript support?

**Comment by ajimae** [comment]
Hi @ThomasLarge

I think the above method of using the `@commercetools/sdk-auth` is fine as the package is specifically suited for this operation.

However, there is another way to retrieve the token from the TS SDK directly.

I don't know if you should be doing this though speaking from a security standpoint. You can hook up a function into the fetch function to retrieve the access-token.

In the TypeScript SDK you can achieve this as follows:

```ts
const fetch = require('node-fetch');

async function fetcher(...args) {

  const r = await fetch(...args),
        t = r.clone(),
        tt = await t.json() // tt will hold value of the token which can be accessed.

  return r
}
```

Then in the `withAnonymousSessionFlow` or using any other auth flows pass in the `fetcher` function as in the example below:

```ts
const anonClient = new ClientBuilder()
  ...
  .withAnonymousSessionFlow({
    ...
   fetch: fetcher
  }).build();

```

I will have a conversation with the team on this to see if we can build in a more secured way of accessing the token outside the SDK.

Thanks

**Comment by ThomasLarge** [comment]
Thanks for that @ajimae, that does work but yeah not ideal for security reasons. I have just noticed that the `sdk-client-v2` does have the option for GraphQL `requestBuilder.graphql()`I can't seem to find any docs for this do you know where I can find them?

**Comment by ajimae** [comment]
Yes, you can send `graphql` queries using the SDK.

To do this, here is an example:

```ts

const {
  ClientBuilder,
  createAuthForClientCredentialsFlow,
  createHttpClient,
} = require('@commercetools/sdk-client-v2')
const { createApiBuilderFromCtpClient } = require('@commercetools/platform-sdk')
const fetch = require('node-fetch')

const customerNumber = 1
const projectKey = process.env.CTP_PROJECT_KEY
const authMiddlewareOptions = {
  host: 'https://auth.europe-west1.gcp.commercetools.com',
  projectKey,
  credentials: {
    clientId: process.env.CTP_CLIENT_ID || '',
    clientSecret: process.env.CTP_CLIENT_SECRET || '',
  },
  oauthUri: process.env.adminAuthUrl || '',
  scopes: [`manage_project:${projectKey}`],
  fetch,
}

const httpMiddlewareOptions = {
  host: 'https://api.europe-west1.gcp.commercetools.com',
  fetch,
}

const client = new ClientBuilder()
  .withProjectKey(projectKey)
  .withClientCredentialsFlow(authMiddlewareOptions)
  .withHttpMiddleware(httpMiddlewareOptions)
  .build()

const apiRoot = createApiBuilderFromCtpClient(client)

// To query all customers
const q = `
  query {
    customers {
     results {
        id 
        email
        firstName,
        lastName
     } 
    }
  }
`;

apiRoot
 .withProjectKey({ projectKey })
 .graphql()
 .post({
   body: {
     query: q,
     variables: { where: `customerNumber in ("${customerNumber}")` }
   }
 })
 .execute()
 .then(customer => {
   console.log(customer.body.data.customers)
 })
 .catch(console.error)

```

This should work.

Also, you can take a look [here](https://docs.commercetools.com/api/graphql) for other graphql queries.

**Comment by ThomasLarge** [comment]
@ajimae Thanks for this, this sorts out our issues. I can't seem to find any docs about GraphQL in the SDK package, can you point me in the right direction?

**Comment by ajimae** [comment]
We don't have it documented in this repository, but we have it documented in our official documentation page [here](https://docs.commercetools.com/api/graphql) there you can find the queries. Once you get a query you wish to execute, you can then use it in the SDK as in the example above.

```ts
const q = `
   // query goes here
`;
```

Then use the query with the apiRoot like this:

```ts
await apiRoot
 .withProjectKey({ projectKey })
 .graphql() // this is the graphql builder method
 .post({ // post your query as part of the request body
   body: {
     query: q, 
     variables: { /** query vairable */ }
   }
 })
 .execute()
```

If you need help with a specific query then you can refer to this [page](https://docs.commercetools.com/api/graphql)
