### ISSUE TITLE
Request body parsing issue with HTTP middleware

### ISSUE THREAD

**Issue by MarkWissinkTekton** [commercetools/commercetools-sdk-typescript#316]
When using `ByProjectKeyGraphqlRequestBuilder` in conjunction with `@commercetools/sdk-middleware-http`, the backend fails to parse the request with the error "Unrecognized token 'object': was expecting (JSON String, Number, Array, Object or token 'null', 'true' or 'false')". The `post` method for `ByProjectKeyGraphqlRequestBuilder` uses a JS object for it's body, but appends a Content-Type header of application/graphql. 
https://github.com/commercetools/commercetools-sdk-typescript/blob/cde61f45563970ca1648496198268976e4f83d8e/packages/platform-sdk/src/generated/client/graphql/by-project-key-graphql-request-builder.ts#L36-L40

This causes issues further down the line when the sdk-middleware-http handles the request. The request body needs to be stringified, but since the Content-Type isn't application/json, the request is sent without a properly parsed request body

https://github.com/commercetools/nodejs/blob/c024c7dfaa82bc2286770d96f0c1b58005bab55e/packages/sdk-middleware-http/src/http.js#L122-L127
```javascript
const body =
        requestHeader['Content-Type'] === 'application/json' &&
          typeof request.body !== 'string'
          ? // NOTE: `stringify` of `null` gives the String('null')
          JSON.stringify(request.body || undefined)
          : request.body
```

Not sure of the best way to resolve the issue, but my current workaround is to override the Content-Type using the `headers` parameter of the `post` method

**Comment by ajimae** [comment]
Hi @MarkWissinkTekton,

Thanks for reporting this issue.

We will look at it and raise a fix ASAP.


Regards

**Comment by ajimae** [comment]
This is done see:
https://github.com/commercetools/commercetools-sdk-typescript/pull/317
[#1807](https://github.com/commercetools/nodejs/pull/1807)

**Comment by MarkWissinkTekton** [comment]
Thanks ajimae!
