### ISSUE TITLE
withExistingTokenFlow should have second argument as optional

### ISSUE THREAD

**Issue by JohnMarsden24** [commercetools/commercetools-sdk-typescript#319]
If you use the `withExistingTokenFlow` middleware TS forces you to provide it two arguments, the first being the `authorization` (token) and the second being `options` which only has one optional value of `force`:

```typescript
interface ExistingTokenMiddlewareOptions = {
  force?: boolean
}

withExistingTokenFlow(authorization: string, options: ExistingTokenMiddlewareOptions): ClientBuilder;
```

Which leads to my scenario when I had to to call the middleware like this:

```typescript
withExistingTokenFlow('random-token', {})
```

Happy to open the PR myself and contribute!

**Comment by ajimae** [comment]
See #320
