### ISSUE TITLE
Support Ticket 17730

### ISSUE THREAD

**Issue by ajimae** [commercetools/commercetools-sdk-typescript#321]
*Summary*
SDK defaulting request headers to application/json

*Details*
Prevent request with header `'Content-Type': 'image/*'` from being overridden to `application/json` by the SDK.

*Context*
https://jira.commercetools.com/browse/SUPPORT-17730

**Comment by ajimae** [comment]
This is done see [this](https://github.com/commercetools/commercetools-sdk-typescript/pull/322)

**Comment by alexbchr** [comment]
When is this fix gonna be released?

**Comment by jenschude** [comment]
Fix has been released with [@commercetools/sdk-client-v2@1.4.1](https://github.com/commercetools/commercetools-sdk-typescript/releases/tag/%40commercetools%2Fsdk-client-v2%401.4.1)
