### ISSUE TITLE
Logger middleware always logs undefined response

### ISSUE THREAD

**Issue by olivvybee** [commercetools/commercetools-sdk-typescript#326]
When we use the logger middleware on our client, the `response` it logs always contains `undefined` for every value.

We're setting up a client like this:

```
const client = new ClientBuilder()
  .withClientCredentialsFlow(credentials)
  .withHttpMiddleware({ host: 'https://api.europe-west1.gcp.commercetools.com/' })
  .withLoggerMiddleware()
  .build();

const apiRoot = createApiBuilderFromCtpClient(client);

const order = await apiRoot
  .withProjectKey({ projectKey })
  .orders()
  .withId({ ID })
  .get()
  .execute();
```

The logs we see show the request details correctly, but it always logs the same thing for the response:

```
Response:  { error: undefined, body: undefined, statusCode: undefined }
```

**Comment by jenschude** [comment]
could you try to add the logger before the http middleware?

**Comment by olivvybee** [comment]
Even with the middlewares swapped around, I still see empty responses in the logs.

**Comment by ajimae** [comment]
Hi @olivvybee 

Please update your @commercetools/sdk-client-v2 to the latest version, this was fixed in the lasted [release](https://github.com/commercetools/commercetools-sdk-typescript/pull/317/files#diff-d872113c6f6834ae35f3dad0619e41a43455cf44654d0a56c774233f86bc5b4aR204)

Thanks

**Comment by ajimae** [comment]
Closing this issue, please feel free to reopen if you are still experiencing this issue.

Thanks

**Comment by olivvybee** [comment]
Sorry for the delayed update, upgrading to 1.4.1 did solve the issue. Thanks!
