### ISSUE TITLE
HTTP Middleware always convert Buffer to json

### ISSUE THREAD

**Issue by alexbchr** [commercetools/commercetools-sdk-typescript#327]
First of all, thanks for fixing issue #321. 

However, it is still impossible to upload product images through the SDK right now, as the Buffer object that gets passed to the SDK gets converted to JSON every time.

Here is my code:
```tsx
const productResult = await ctApiRoot
    .withProjectKey({ projectKey })
    .products()
    .withId({ ID: id })
    .images()
    .post({
      queryArgs: {
        sku,
      },
      headers: {
        'Content-Type': contentType as 'image/png' | 'image/jpeg',
      },
      body: req.rawBody as Buffer,
    })
    .execute()
```

Just before this code, I tried to log `req.rawBody`, which is effectively a `Buffer` object. I also even tried `Buffer.isBuffer(req.rawBody)` to be sure.

However, I always get an error saying that "Image data can't be read as image/png. Possibly corrupted?". Saving the buffer to the local file system works just fine. After digging a bit, I tried logging `fetchOptions` just [here](https://github.com/commercetools/commercetools-sdk-typescript/blob/02f385397a9bae3cb67b38c530e35a619fe94e3f/packages/sdk-client/src/sdk-middleware-http/http.ts#L168) and realized that the Buffer was getting converted to JSON before the query is sent to commercetools:

![image](https://user-images.githubusercontent.com/3542313/190663246-f5e952a7-ff4b-49d5-887c-20e2d74d2239.png)

# Expected Behavior
The body should remain a `Buffer` before being sent to commercetools.

**Comment by ajimae** [comment]
Hi @alexbchr 

Let me look into this, I will get back to you ASAP.

Thanks
