### ISSUE TITLE
Incorect request pathVariables

### ISSUE THREAD

**Issue by wkrugiolka-rewe-digital** [commercetools/commercetools-sdk-typescript#33]
Request is not correct when i try query for prices. The code i run is:
apiRoot
.withProjectKeyValue('qwertyuiop')
.prices()
.importSinkKeyWithImportSinkKeyValue("12345")
.post({
    body: { name: 'product-type-name', description: 'some description' },
  })
.execute()
.then((x) => {
    console.log(x);
})
.catch((e) => {
    console.log(e);
});

and the request looks like this:

originalRequest: {
    baseUri: 'https://import.europe-west1.gcp.commercetools.com',
    method: 'POST',
    uriTemplate: '/{projectKey}/prices/importSinkKey={importSinkKey}',
    pathVariables: {
      '0': '1',
      '1': '2',
      '2': '3',
      '3': '4',
      '4': '5',
      '5': 'y',
      '6': 'u',
      '7': 'i',
      '8': 'o',
      '9': 'p'
    },
    headers: { 'Content-Type': 'application/json', Authorization: [Array] },
    body: { name: 'product-type-name', description: 'some description' },
    uri: '/{projectKey}/prices/importSinkKey={importSinkKey}'
  }

so the pathVariables looks like some kind of merge of projectKey and sink

**Comment by jenschude** [comment]
Sorry for the late reply, but the arguments have to be filled in using an object:

```
apiRoot
  .withProjectKeyValue({projectKey: 'qwertyuiop'})
  .prices()
  .importSinkKeyWithImportSinkKeyValue({importSinkKey:"12345"})
```
