### ISSUE TITLE
There is no possibility to add custom type for standalone-price

### ISSUE THREAD

**Issue by iurii-untilov** [commercetools/commercetools-sdk-typescript#345]
Hello,

As ResourceTypeId type doesn't include yet 'standalone-price' it is not possible to add a custom type for it using typescript SDK.
See https://github.com/commercetools/commercetools-sdk-typescript/blob/master/packages/platform-sdk/src/generated/models/type.ts#L266

Thanks.

[PR Link
](https://github.com/commercetools/commercetools-docs/pull/2376)

**Comment by ajimae** [comment]
This is done and will be available in the next release.

Thanks
