### ISSUE TITLE
Support persisting anonymous sessions between page reloads.

### ISSUE THREAD

**Issue by YGKtech** [commercetools/commercetools-sdk-typescript#353]
Apologies if this isn't the right place for this, or if there's already a solution to my problem which I've somehow missed.

I'm trying to find a way to keep an anonymous user session alive after a user refreshes the page, e.g. so an anonymous user could load the page, add an item to a cart, reload/navigate away, then return and check out their cart.

I'm not seeing any mention of this topic in the docs, or any obvious support for it in the codebase. I did note that the anonymous auth flow accepts an anonymous_id parameter, so I tried capturing the id generated during the oauth flow, storing it in localStorage, and passing it in after a page reload, but this results in an error because the id is 'already in use'. I also tried passing in a custom tokenCache object which would read & write localStorage, but the SDK code never actually makes calls to my tokenCache (seems there's an old issue about this here: https://github.com/commercetools/commercetools-sdk-typescript/issues/140 which nobody ever responded to so it was auto-closed).
I imagine there may be a way for me to accomplish this by capturing the access token and passing it in to the ExistingToken auth flow, I'll likely try that next, though even if it works I'm not sure I'd consider it a production-ready solution, I'm having to jump through hoops to read the access token, and having to conditionally use a different auth flow is a bit clunky.

Normally when integrating an API/SDK like this, I would expect to implement this sort of functionality myself. So I'm really not opposed to having to do some of this work myself, but the SDK is already trying to automate a lot of the token handling, so it seems like a feature that should already be built in, and it doesn't expose the token value anywhere, so I had to pass in a modified copy of `fetch` to capture the token data.

**Comment by ajimae** [comment]
Hi @YGKtech 

Thanks for bringing this up. For anonymous authentication flow, the anonymous ID is used to get an anonymous token which is then cached in the `tokenCache` using a `tokenCacheKey` [here](https://github.com/commercetools/commercetools-sdk-typescript/blob/70db08858547cfddc7601269a9a488cb85e5699d/packages/sdk-client/src/sdk-middleware-auth/base-auth-flow.ts#L69), all subsequent requests should now use the cached token instead provided it's still within the same request-response session. To a good extent SDK automates this process of token handling.

Another thing I would suggest is to capture and save the `anonymous token` gotten after the first request and then use it in the `headers` of the subsequent request, note that here you are now managing your own `tokenCache`.

For the issue about the SDK not making calls to the auth token will be investigated and see if we can reproduce it on our end and why that is the case.


Thanks.

**Comment by YGKtech** [comment]
Thanks for the response @ajimae 
To clarify - the token created by the anonymous authentication flow **is** being used on subsequent requests as expected.  The problem I'm having is that I want to make the SDK reuse that token even if the user refreshes the page. Right now, if a user refreshes the page, they are given a new token associated with a new anonymous ID. This means that if a user adds an item to their cart, then refreshes the page, they will not see that item in their cart because the new anonymous ID does not have access to the cart created with the previous one. By storing the token in the browser's `localStorage` and reusing that stored token as long as it remains valid, users could reload the page as many times as they want and they would still have the same anonymous ID.

I have attempted to implement this behavior myself by passing in a custom `tokenCache` implementation which keeps the token in localStorage until it expires. But, if you look at the code for the anonymous session flow here: https://github.com/commercetools/commercetools-sdk-typescript/blob/70db08858547cfddc7601269a9a488cb85e5699d/packages/sdk-client/src/sdk-middleware-auth/anonymous-session-flow.ts#L16 you will see that the function creates its own instance of `tokenCache` rather than first checking to see if one was provided in the `options` object. The tokenCache it creates works properly, so the token is reused on subsequent requests, but I am unable to implement the behavior I want because it always uses the default tokenCache instead of the custom one I am providing.
Compare this to the client credentials flow: https://github.com/commercetools/commercetools-sdk-typescript/blob/70db08858547cfddc7601269a9a488cb85e5699d/packages/sdk-client/src/sdk-middleware-auth/client-credentials-flow.ts#L18 and you'll see that it only creates a new `tokenCache` instance if `options.tokenCache` is undefined.

Making the anonymous flow check this parameter in the same way should enable me to implement the functionality I want, without changing the default behavior of the library.

Thanks.

**Comment by ajimae** [comment]
Hi @YGKtech 

Please look at this [PR](https://github.com/commercetools/commercetools-sdk-typescript/pull/355) I believe this will fix the issue.

Thanks

**Comment by YGKtech** [comment]
@ajimae : Thanks, I installed the updated version and was able to get my custom tokenStore code working as I wanted.

Here's the code I'm using to make it so anonymous session tokens are reused after the page reloads, in case anyone else views this issue looking for a way to do the same, or if the team wants to try adding similar functionality to the SDK as a configurable option for the anonymous session flow.
```
const ANONYMOUS_TOKEN_STORAGE_KEY = 'ct-anonymous-token';

export function makePersistentTokenCache(): TokenCache {
  let current: TokenStore | {} = {};

  const storedValue = localStorage.getItem(ANONYMOUS_TOKEN_STORAGE_KEY);
  if (storedValue) {
    const parsed = JSON.parse(storedValue) as TokenStore;
    if ('expirationTime' in parsed && parsed.expirationTime >= Date.now()) {
      current = parsed;
    } else {
      localStorage.removeItem(ANONYMOUS_TOKEN_STORAGE_KEY);
      current = {};
    }
  }

  return {
    get: (tokenCacheOptions?: TokenCacheOptions) => {
      if (current) {
        return current as TokenStore;
      }
      const storedValue = localStorage.getItem(ANONYMOUS_TOKEN_STORAGE_KEY);
      if (storedValue) {
        const parsed = JSON.parse(storedValue) as TokenStore;
        if ('expirationTime' in parsed && parsed.expirationTime >= Date.now()) {
          current = parsed;
        } else {
          localStorage.removeItem(ANONYMOUS_TOKEN_STORAGE_KEY);
          current = {};
        }
        return current as TokenStore;
      }
      return {} as TokenStore;
    },
    set: (newValue: TokenStore, tokenCacheOptions?: TokenCacheOptions) => {
      current = newValue;
      localStorage.setItem(ANONYMOUS_TOKEN_STORAGE_KEY, JSON.stringify(current));
      return current;
    },
  }
}

const anonymousSessionAuthMiddlewareOptions = {
  host: 'https://auth.us-central1.gcp.commercetools.com',
  projectKey: '<projectKey goes here>',
  credentials: {
    clientId: '<clientId goes here>',
    clientSecret: '<clientSecret goes here>',
  },
  scopes: [
    'create_anonymous_token:liquor-club',
    'manage_my_quote_requests:liquor-club',
    'manage_my_business_units:liquor-club',
    'manage_my_shopping_lists:liquor-club',
    'manage_my_payments:liquor-club',
    'manage_my_profile:liquor-club',
    'manage_my_quotes:liquor-club',
    'manage_my_orders:liquor-club',
    'view_categories:liquor-club',
    'view_published_products:liquor-club',
  ],
  fetch,
  tokenCache: makePersistentTokenCache()
}

const anonymousSessionClient = new ClientBuilder()
  .withProjectKey('<projectKey goes here>')
  .withAnonymousSessionFlow(anonymousSessionAuthMiddlewareOptions)
  .withHttpMiddleware(httpMiddlewareOptions)
  .withUserAgentMiddleware()
  .build()
```

One more thing, in my code above, you'll see that I return `{}` when I don't have a valid token available. This matches the behavior of the `store` the SDK uses by default: https://github.com/commercetools/commercetools-sdk-typescript/blob/5e61cc76d8a6442310adf91fdf473549af13036c/packages/sdk-client/src/sdk-middleware-auth/utils.ts#L1-L10 
when it is given an initial value of `{}`, as it usually is, like in your recent update to the anonymous session flow: https://github.com/commercetools/commercetools-sdk-typescript/blob/5e61cc76d8a6442310adf91fdf473549af13036c/packages/sdk-client/src/sdk-middleware-auth/anonymous-session-flow.ts#L16 
This works perfectly fine, but it actually conflicts with the type definitions for `tokenCache`: https://github.com/commercetools/commercetools-sdk-typescript/blob/5e61cc76d8a6442310adf91fdf473549af13036c/packages/sdk-client/src/types/sdk.d.ts#L261-L264 
which indicate that the `get()` method of tokenCache should always return a fully formed `TokenStore` object, even if one is not available. To prevent type errors, I have to cast `{} as TokenStore` in my code.
The default `store` the SDK uses internally actually doesn't use this type definition, which is probably why the inaccurate type definition hasn't been noticed before. I think the simplest solution would be to update the type definitions to allow `get()` to return `{}`. It might be better to return `undefined` when no token is available, but that may require more extensive updates to the codebase.

But, my code is functioning the way I need it to now, so this is just a suggestion, thanks very much for you help :)
