### ISSUE TITLE
Retry not fired on request timeout

### ISSUE THREAD

**Issue by olup** [commercetools/commercetools-sdk-typescript#354]
It seems the client is not retrying when we are adding a timeout (using native node 18 `fetch`and `abortController`) - at least our datadog traces don't show any retries.

We get the "Network error: User aborted a request" error from CT client though.

If I understand correctly the code, it should retry independently of the `errorCodes` array because aborting will throw at fetch ("network") level, not as a http error, am I right ?

This is roughly the client and http middleware declaration, can you spot anything wrong with it ?

```
      const authMiddlewareOptions: AuthMiddlewareOptions = {
        host: `https://auth.${REGION}.gcp.commercetools.com`,
        projectKey: config.environment.COMMERCETOOLS_PROJECT_KEY,
        credentials: {
          clientId: config.environment.COMMERCETOOLS_CLIENT_ID,
          clientSecret: config.environment.COMMERCETOOLS_CLIENT_SECRET,
        },
        scopes: SCOPES,
      };


const httpMiddlewareOptions: HttpMiddlewareOptions = {
        host: `https://api.${REGION}.gcp.commercetools.com`,
        getAbortController: () => new AbortController(),
        timeout: 2000,
        enableRetry: true,
        retryConfig: {
          maxRetries: 2,
          retryCodes: [
            504,
            500,
            'ETIMEDOUT',
            'ECONNREFUSED',
            503,
          ],
        },
      };


      const ctpClient = new ClientBuilder()
        .withProjectKey(config.environment.COMMERCETOOLS_PROJECT_KEY)
        .withClientCredentialsFlow(authMiddlewareOptions)
        .withHttpMiddleware(httpMiddlewareOptions)
        .build();
```

**Comment by ajimae** [comment]
Hi @olup,

Currently what we have with the SDK doesn't retry the request on `timeout` once a request times out we abort the request. We don't currently have a retry on aborted requests.

However, we can look into this and see if it's a feature we could implement then we will certainly implement it.

Thanks

**Comment by olup** [comment]
Hi @ajimae thanks for the reply but I am not sure that I understand. From [here](https://github.com/commercetools/commercetools-sdk-typescript/blob/master/packages/sdk-client/src/sdk-middleware-http/http.ts#L290) it seems the client will retry if fetch throws, which is what is supposed to happen when the `abortcontroller` kill the signal after the timeout kicks in (see [here](https://github.com/commercetools/commercetools-sdk-typescript/blob/master/packages/sdk-client/src/sdk-middleware-http/http.ts#L173)). So are you sure the client isn't supposed to retry on request timeout ?

If you can point me to what I understand wrong I'll be happy to make a PR to have retry on timeout - which seems a very desirable feature : when taking more than a second, or half second, we'd like to kill CT request and retry.

**Comment by ajimae** [comment]
Hi @olup 

I was able to get the SDK to retry on abort.

The network status (error) code is `0` and the message is `The user aborted a request`, so you can use this config to get it to retry on request abort.

```ts
const httpMiddlewareOptions = {
  ...
  timeout: 2000,
  getAbortController: () => new AbortController(),
  enableRetry: true,
  retryConfig: {
    maxRetries: 3,
    retryDelay: 200,
    backoff: true,
    retryCodes: [0], // or ['The user aborted a request']
  }
}
```

**Comment by olup** [comment]
@ajimae thanks for your help, but your proposal did not work in our codebase, and reading from the source code I am wondering if it works for you too (I mean, if that's the thing that makes it work - I don't doubt it does work)

**Comment by olup** [comment]
It was pointed to me that the commercetools client code actually does not recreates the abort controller when a retry happen, which would lead to instant aborted fetch calls once the signal has been aborted once before. We'll test this, but if it happens to be the case would you accept a PR of it does fix the problem ?

**Comment by mh-flink** [comment]
The pull request above allows to retry aborted requested explicitly. More details see PR.

**Comment by ajimae** [comment]
This is now done.

**Comment by olup** [comment]
Cheers ! Do you know when can we expect a release with the fix ?
