### ISSUE TITLE
Is there a way to revoke a token?

### ISSUE THREAD

**Issue by harm-meijer** [commercetools/commercetools-sdk-typescript#362]
I have searched through the code for "revoke" but could not find anything, not sure where the complete documentation for this is, the only documentation I found covers getting started but no complete documentation of the methods.

So the question is: can I [revoke a token](https://docs.commercetools.com/api/authorization#revoking-tokens) with the sdk? I'm asking because the sdk is used on a stateless server and this token is only used for the duration of the request.

**Comment by jenschude** [comment]
The SDK didn't implement a revoke token mechanism yet.

The revocation typically happens out of band and was not in scope of the SDK. Same applies btw for the introspection.

**Comment by harm-meijer** [comment]
@jenschude Can you advice how I should use the sdk on a stateless server? I don't think it's a good idea to create a new session (associated with token) on every request only to never use that token again.

**Comment by jenschude** [comment]
There are different ways possible.

One could be using a cache instance for storing the tokens and using the existing tokens middleware.

Another one can be to give the token to the serverless function using an environment variable. You would have to have a service/library regularly updating the environment variable.

When using AWS Lambda you could also use SSM or similar functionality.

Another option for AWS Lambda is to use the init phase of the lambda function to create the client instance and fetching the token. The lambda instance should stay alive for some time (~15min) before being killed.
