### ISSUE TITLE
Missing Typings for ES6

### ISSUE THREAD

**Issue by dhemeier** [commercetools/commercetools-sdk-typescript#37]
Currently when you try to install the latest versions of the @commercetools/xxxx packages, no typings are present to run with TypeScript.

**Steps to reproduce**
1) Clean `npm init` project
2) Install required packages:
```
npm install --save @commercetools/platform-sdk
npm install --save @commercetools/importapi-sdk
npm install --save @commercetools/ml-sdk
```
3) No typings for `@commercetools/sdk-client`, `@commercetools/sdk-middleware-auth` and `@commercetools/sdk-middleware-http`

The first example I used is based on the your [current documentation](https://commercetools.github.io/nodejs/sdk/api/typescriptSdk.html). I also tried the `ES6` example from the merchant center:

```
import { createClient } from '@commercetools/sdk-client'
import { createAuthMiddlewareForClientCredentialsFlow } from '@commercetools/sdk-middleware-auth'
import { createHttpMiddleware } from '@commercetools/sdk-middleware-http'


const projectKey = 'xxxxxx'

const authMiddleware = createAuthMiddlewareForClientCredentialsFlow({
    host: 'https://auth.europe-west1.gcp.commercetools.com',
    projectKey,
    credentials: {
        clientId: 'xxxxxxxx',
        clientSecret: 'xxxxxxxxx',
    },
    scopes: ['xxxxxxx'],
})
const httpMiddleware = createHttpMiddleware({
    host: 'https://api.europe-west1.gcp.commercetools.com',
})
const client = createClient({
    middlewares: [authMiddleware, httpMiddleware],
})
```

I also tried to install `@commercetools/typescript-sdk` manually without success. Maybe I missed some needed config to get the typings? 

Thanks in advance
Dennis Hemeier

**Comment by najibla** [comment]
Same for me..

**Comment by AlexW-Valtech** [comment]
Experiencing the same - are these planned to be included? We've had to declare the types within our repo.

**Comment by jenschude** [comment]
Sadly there are no type definitions atm available for the nodejs client.

And we are aware of this and we plan on integrating a client directly in the SDK itself written in Typescript.
