### ISSUE TITLE
Error Missing required options with version 2.1.0 trying withRefreshTokenFlow

### ISSUE THREAD

**Issue by harm-meijer** [commercetools/commercetools-sdk-typescript#384]
I have the following to set up my client:

```typescript
type Config = {
  clientId: string
  clientSecret: string
  projectKey: string
  authUrl: string
  apiUrl: string
}

function createCtpClient(
  { clientId, clientSecret, projectKey, authUrl, apiUrl }: Config,
  tokenCache: TokenCache,
  refreshToken?: string
) {
  const packageJson = getPackageJson()
  let client = new ClientBuilder()
  const authFlowParams = {
    host: authUrl,
    projectKey,
    credentials: {
      clientId,
      clientSecret,
    },
    ...(refreshToken ? { refreshToken } : {}),
    fetch,
    tokenCache,
  }
  console.log('authFlowParams:', authFlowParams)
  if (refreshToken) {
    //@ts-ignore
    client = client.withRefreshTokenFlow(authFlowParams)
  } else {
    client = client.withClientCredentialsFlow(authFlowParams)
  }
  return client
    .withHttpMiddleware({
      maskSensitiveHeaderData: true,
      host: apiUrl,
      enableRetry: true,
      retryConfig: {
        retryCodes: [500, 502, 503, 504],
      },
      fetch,
    })
    .withQueueMiddleware({ concurrency: getConcurrency().ctpConcurrency })
    .withUserAgentMiddleware({
      libraryName: packageJson.name,
      libraryVersion: packageJson.version,
      contactUrl: packageJson.homepage,
      contactEmail: packageJson.author.email,
    })
    .build()
}

const getApiRoot = ((apiRoot?: ByProjectKeyRequestBuilder) => {
  let expires: number
  let token: TokenStore
  const tokenCache: TokenCache = (() => {
    const get = () => {
      return token
    }
    const set = (cache: TokenStore) => {
      console.log('got cache', cache)
      expires = cache.expirationTime
      token = cache
    }
    return { get, set }
  })()

  return () => {
    const clientConfig = getClientConfig()
    let refreshToken: string | undefined
    if (apiRoot && Date.now() >= expires) {
      apiRoot = undefined
      refreshToken = token.refreshToken
    }
    if (apiRoot) {
      return apiRoot
    }

    apiRoot = createApiBuilderFromCtpClient(
      createCtpClient(clientConfig, tokenCache, refreshToken)
    ).withProjectKey({
      projectKey: clientConfig.projectKey,
    })
    return apiRoot
  }
})()
```

I hope this will refresh the token when `Date.now() >= expires` and then resets the token cache with the new token and expiration time, had to update to version 2.1.0 because the version I had did not allow tokenCache in RefreshAuthMiddlewareOptions but now it will error with  `Missing required options` somewhere in authMiddlewareBase 

```javascript
  if (tokenObj && tokenObj.refreshToken && (!tokenObj.token || tokenObj.token && Date.now() > tokenObj.expirationTime)) {
    console.log("difference:",Date.now() - tokenObj.expirationTime)
    console.log('tokenObj:',tokenObj)
    console.log('userOptions:',userOptions)
```

The logs are: 

```
    difference: 17 
    tokenObj: {
      token: 'my-token',
      expirationTime: 1669314866676,
      refreshToken: 'refresh-token'
    }
   userOptions: undefined
```

I am using mock service worker in my test and capture the token request with the following response:

```typescript
      rest.post('*/oauth/token', (req, res, ctx) => {
        return res(
          ctx.status(200),
          ctx.json({
            access_token: 'my-token',
            expires_in: 30,
            refresh_token: 'refresh-token',
            scope: 'my-scope',
            token_type: 'Bearer',
          })
        )
      })
```

The log of the authFlowParams is:

```
    authFlowParams {
      host: 'https://auth.europe-west1.gcp.commercetools.com',
      projectKey: 'mc-project',
      credentials: {
        clientId: '123456789012345678901234',
        clientSecret: '12345678901234567890123456789012'
      },
      refreshToken: 'refresh-token',
      fetch: [Function (anonymous)],
      tokenCache: { get: [Function: get], set: [Function: set] }
    }
```

Calling the apiRoot in the following way in my test:

```typescript
getApiRoot()
    .productProjections()
    .search()
    .get({ queryArgs })
    .execute()
```

The first time it passes because it crates a new client, the second time the token is expired so it calls withRefreshTokenFlow and that causes this error.

**Comment by harm-meijer** [comment]
When I started messing with `node_modules/@commercetools/sdk-client-v2/dist/commercetools-sdk-client-v2.cjs.dev.js` some more I found the function `createAuthMiddlewareForRefreshTokenFlow$1` and at the end it calls `authMiddlewareBase(params);` changed that to `authMiddlewareBase(params, next, options);` and got my test to pass, as it did a successful token refresh. I think `createAuthMiddlewareForRefreshTokenFlow` forgot to pass the 3rd argument to `authMiddlewareBase`

**Comment by ajimae** [comment]
@harm-meijer 

Thanks for opening this issue, currently the SDK is only allowed to refresh a token that is associated with a user. Example can be seen [here](https://github.com/commercetools/commercetools-sdk-typescript/blob/3d4149d582cbcecb0b17c2bae7fc783590613bdc/packages/sdk-client/src/sdk-middleware-auth/password-flow.ts#L42).

https://github.com/commercetools/commercetools-sdk-typescript/blob/3d4149d582cbcecb0b17c2bae7fc783590613bdc/packages/sdk-client/src/sdk-middleware-auth/password-flow.ts#L42

However, I will have to look into it and see if we can extend this to allow token refresh for other auth flows as well.

I will revert with an update once we come up with a decision on this.


Thanks.

**Comment by harm-meijer** [comment]
@ajimae 
Thank you for your reply, I think I can do with just re creating a new token since this is on a server and `withClientCredentialsFlow` probably returns a token that is good for days.

**Comment by harm-meijer** [comment]
@ajimae I see this problem was caused by my mock service worker returning the wrong response [client credentials flow](https://docs.commercetools.com/api/authorization#client-credentials-flow) is not supposed to return a refresh token, even if this is changed in the sdk code the commercetools api will not return such a token.

**Comment by miticm** [comment]
> @harm-meijer
> 
> Thanks for opening this issue, currently the SDK is only allowed to refresh a token that is associated with a user. Example can be seen [here](https://github.com/commercetools/commercetools-sdk-typescript/blob/3d4149d582cbcecb0b17c2bae7fc783590613bdc/packages/sdk-client/src/sdk-middleware-auth/password-flow.ts#L42).
> 
> https://github.com/commercetools/commercetools-sdk-typescript/blob/3d4149d582cbcecb0b17c2bae7fc783590613bdc/packages/sdk-client/src/sdk-middleware-auth/password-flow.ts#L42
> 
> However, I will have to look into it and see if we can extend this to allow token refresh for other auth flows as well.
> 
> I will revert with an update once we come up with a decision on this.
> 
> Thanks.

Any updates on this? I want to use refresh flow on anonymous tokens as well, thanks
