### ISSUE TITLE
When trying to use type ByProjectKeyRequestBuilder, eslint is complain about the import

### ISSUE THREAD

**Issue by phofmann** [commercetools/commercetools-sdk-typescript#386]
When trying to create a const of type ByProjectKeyRequestBuilder like
`  const builder: ByProjectKeyRequestBuilder = createApiBuilderFromCtpClient(ctpClient).withProjectKey({
    projectKey: config.projectKey || "",
  });`
you will need to import ByProjectKeyRequestBuilder. E.g VSCode does this for you like 

`import { ByProjectKeyRequestBuilder } from "@commercetools/platform-sdk/dist/declarations/src/generated/client/by-project-key-request-builder";`

but then complains about it:
`

module "./node_modules/.pnpm/@commercetools+platform-sdk@4.2.0/node_modules/@commercetools/platform-sdk/dist/declarations/src/generated/client/by-project-key-request-builder"
Unable to resolve path to module '@commercetools/platform-sdk/dist/declarations/src/generated/client/by-project-key-request-builder'.eslint[import/no-unresolved](https://github.com/import-js/eslint-plugin-import/blob/v2.26.0/docs/rules/no-unresolved.md)
`

**Comment by ajimae** [comment]
Hi @phofmann 

Are you still experiencing this issue? As you can see eslint is not complaining on my end.

![Screen Shot 2023-01-03 at 16 48 40](https://user-images.githubusercontent.com/32770340/210392115-e986393b-2c8e-4044-952b-1690391df526.png)
eslint` related issue?

**Comment by phofmann** [comment]
Hi,
thanks for asking. Works now. Might have been, that I was on an older version of the API. Sorry
