### ISSUE TITLE
Getting some error in the terminal

### ISSUE THREAD

**Issue by satyam21041997** [commercetools/commercetools-sdk-typescript#389]
Hi,
I tried to install node modules in this project. After running npm install command I am getting some error:-
![image](https://user-images.githubusercontent.com/94686066/204196122-b6e7cd0f-796b-42ac-8ede-1495ff491d08.png)

**Comment by ajimae** [comment]
Hi @satyam21041997 

From the screenshot you posted, I can see this is not an issue with the SDK rather, `EPERM` is an issue that arises when you do not have enough (administrative) permission to write some project files and/or binaries to certain location in your windows system.

Try running the command for the first time as an administrator or login as an administrator. Also you can take a look at this [so answer](https://stackoverflow.com/a/34614939)

Thanks
