### ISSUE TITLE
Product projections search endpoint is missing POST body

### ISSUE THREAD

**Issue by lojzatran** [commercetools/commercetools-sdk-typescript#41]
When doing search requests, it should be also possible to send the parameters in a body of a POST request according to the docs: https://docs.commercetools.com/api/projects/products-search#query-parameters

However, it is currently not supported by the sdk. There is no way to pass body to the post method and the method itself also returns `ApiRequest<void>`: https://github.com/commercetools/commercetools-sdk-typescript/blob/master/packages/platform-sdk/src/generated/client/search/by-project-key-product-projections-search-request-builder.ts

**Comment by jenschude** [comment]
Closed with 71781a9

**Comment by jenschude** [comment]
Released with version 1.10.0
