### ISSUE TITLE
Unable to set custom fields on addresses during resource creation

### ISSUE THREAD

**Issue by cq-fpietron** [commercetools/commercetools-sdk-typescript#412]
Hello,

Even though the [docs state you can pass a `custom` property to the `shippingAddress` when creating my cart](https://docs.commercetools.com/api/types#addressdraft), trying to do so results in TypeScript errors (`MyCartDraft` utilises `BaseAddress`).

A similar situation occurs when adding an address to a customer profile: I have to resort to a separate customer update just to set some custom fields on a customer address.

Could you please review whether these address APIs are handled correctly by the SDK?

Best regards

**Comment by ajimae** [comment]
Hi @cq-fpietron 

Can you please provide the structure of the custom field you are trying to pass and also the specific TypeScript types error you are experiencing?

Thanks

**Comment by cq-fpietron** [comment]
@ajimae the following simplified request builder syntax
```ts
.carts()
      .post({
        body: {
          shippingAddress: {
            country: 'PL',
            custom: {
              type: {
                key: 'some-key',
                typeId: 'type',
              },
              fields: {},
            },
          },
        },
      })
      .execute();
```

results in the following error:
```
(property) custom: {
    type: {
        key: string;
        typeId: string;
    };
    fields: {};
}
Type '{ country: string; custom: { type: { key: string; typeId: string; }; fields: {}; }; }' is not assignable to type 'BaseAddress'.
  Object literal may only specify known properties, and 'custom' does not exist in type 'BaseAddress'.ts(2322)
me.d.ts(76, 14): The expected type comes from property 'shippingAddress' which is declared here on type 'MyCartDraft'
```

**Comment by ajimae** [comment]
Hi @cq-fpietron 

I think [this](https://docs.commercetools.com/api/projects/carts#set-shipping-address-customfield) is the endpoint you are looking for on how to set customFields for `shippingAddress`

There is no `custom` property on  the `shippingAddress` field which is of type `BaseAddress`.


Thanks

**Comment by cq-fpietron** [comment]
@ajimae thing is if I ignore the TypeScript errors, the SDK works as expected from the docs I linked and adds the custom fields to the shipping address. It seems that there are some inconsistencies in your TS declaration generation.

**Comment by ajimae** [comment]
@cq-fpietron this issue has been fixed [here](https://github.com/commercetools/rmf-codegen/commit/89bdc752a0bbf77b778052eb9ea9a929d1b83b2e) and it is part of this PR #411, we will merge it and release it in the next SDK release.


Thanks
