### ISSUE TITLE
Unhandled error thrown when using includeRequestInErrorResponse: false in sdk-client-v2

### ISSUE THREAD

**Issue by cq-fpietron** [commercetools/commercetools-sdk-typescript#414]
Hello,

a bug that I encountered comes from L707 in `commercetools-sdk-client-v2.cjs.dev.js`:

```ts
 if (statusCode === 404) errorMessage = `URI not found: ${rest.originalRequest.uri}`;
 ```
 
 when initialising the HTTP middleware with `includeRequestInErrorResponse: false` and receiving a 404 response from CT, the line above results in an error caused by trying to reference `uri` on `originalRequest` that does not exist:
 
 ```
 TypeError: Cannot read properties of undefined (reading 'uri')
   at createError (/api/node_modules/@commercetools/sdk-client-v2/dist/commercetools-sdk-client-v2.cjs.dev.js:707:81)
 ```

is this expected behaviour?

Regards

**Comment by ajimae** [comment]
Fixed.
