### ISSUE TITLE
GraphQLError type generated from Commercetools API does not match "canonical" graphql-js GraphQL error

### ISSUE THREAD

**Issue by ghost** [commercetools/commercetools-sdk-typescript#419]
Hello.

## What's wrong

I noticed that the `GraphQLError` type in `@commercetools/platform-sdk` at:
https://github.com/commercetools/commercetools-sdk-typescript/blob/026d91a747b445b0913eabb7eb91ecc7f3eb257e/packages/platform-sdk/src/generated/models/graph-ql.ts#L7

is different than the `GraphQLError` from the `graphql` (aka `graphql-js`) package:
https://github.com/graphql/graphql-js/blob/main/src/error/GraphQLError.ts#L41

Namely, the `GraphQLError` seen in this repo has fewer fields, for example, it's missing the `extensions` field.

Here's a CodeSandbox example that shows how this can conflict with other packages in the GraphQL ecosystem (line 12):

(rhe platform-sdk package sometimes doesn't install in Codesadnbox for some reason, despite being in package.json. If you get a `could not find type declarations` error, please change the version of platform-sdk to 4.3.0 then switch it back to 4.4.0 - that should force-install)

https://codesandbox.io/s/typescript-playground-export-forked-00ifsx?file=/index.ts

## Proposed solution
Add `graphql` as a dependency to `@commercetools/platform-sdk` and use `GraphQLError` from that package rather than the `GraphQLError` generated from Commercetools.

## Thoughts
I've been thinking that this is intentional, because e.g. Commercetools GraphQL API could have some alternative implementation that doesn't return those fields, but it's not the case.

If I query the real Commercetools GraphQL API with a malformed query, it actually returns an error with the `extensions` field, while the typedef in this repo doesn't have it.

It seems to me as if the runtime is de-synced from the typedefs.

Here you can see the extensions field being returned, despite not being in the GraphQLError typedefs in platform-sdk:

<img width="800" alt="image" src="https://user-images.githubusercontent.com/5359825/215100194-42399d12-6257-421d-8e27-4b3f7fa45ea4.png">

**Comment by MarkWissinkTekton** [comment]
@ajimae any updates on this? We use data from errors to run logic, like retrying a request using the `currentVersion` from the [ConcurrentModificationError](https://docs.commercetools.com/import-export/error#concurrentmodificationerror). This API change caused an unexpected breakage since the error data was moved from the base of the object into the `extensions` field.

**Comment by jenschude** [comment]
Hi,

we opened a PR in the upstream repository which updates the definition of the GraphQLError and adds the extension field. This will also include type definitions for the error object itself.

**Comment by jenschude** [comment]
I just triggered the release which includes the changes to the GraphQL error response in the Typescript SDK.

As already mentioned the types of each error are now also included in the SDK.

**Comment by jenschude** [comment]
Details can be seen here: https://github.com/commercetools/commercetools-sdk-typescript/releases/tag/%40commercetools%2Fplatform-sdk%404.7.0
