### ISSUE TITLE
The new GoogleCloudFunction destination is not supported in @commercetools/platform-sdk 4.5.0

### ISSUE THREAD

**Issue by sfernengel** [commercetools/commercetools-sdk-typescript#430]
Currently I am using the following workaround

```ts
/**
 * Use extensionDraft:any instead of ExtensionDraft until they
 * add GoogleCloudFunction to the SDK
 */
const extensionDraft: any = {
    key: "tt-order-checker",
    destination: {
        type: "GoogleCloudFunction",
        url: "https://europe-west1-ct-support.cloudfunctions.net/training-extensions-sample"
    },
    triggers: [{
        resourceTypeId: "order",
        actions: ["Create"]
    }]
}
```

**Comment by ajimae** [comment]
@sfernengel 

This has been fix [here](https://github.com/commercetools/commercetools-sdk-typescript/blob/40db998f8a8e2a314cea8eb1146f1f035eebd507/packages/platform-sdk/src/generated/models/extension.ts#L81)

Update your [@commercetools/platform-sdk](https://www.npmjs.com/package/@commercetools/platform-sdk/v/4.6.0) package to the latest release.

Thanks
