### ISSUE TITLE
ActiveCart endpoint for store-context is missing queryArgs

### ISSUE THREAD

**Issue by asgerjensen** [commercetools/commercetools-sdk-typescript#446]
```
 this.client.
          withProjectKey({ projectKey: 'abc '}).
          inStoreKeyWithStoreKeyValue({ storeKey: 'foo'}).
          me().
          activeCart().get({})
```

This does not allow adding queryArgs, so its not possible to set `expand` for instance.

Current behavior:
- Unable to set expand= on the query string

Expected behavior:
- Able to set expand on the query string, like on all other cart endpoints.

**Comment by anjaliVashisth** [comment]
Migrated to Jira https://commercetools.atlassian.net/browse/DEVX-287
