### ISSUE TITLE
Using Client Credentials flow from a public client (web browser, mobile app, desktop app) creates a cybersecurity vulnerability

### ISSUE THREAD

**Issue by mikehans** [commercetools/commercetools-sdk-typescript#456]
re: https://github.com/commercetools/commercetools-sdk-typescript/blob/master/examples/react-vite/src/lib/ClientBuilder.ts

The client credentials flow is a confidential client flow, yet it is being used in a public client. This creates a security vulnerability by exposing the client secret to anyone who cares to read the source code. The client secret doesn't expire - it can only be replaced administratively.

The client credentials flow is intended for use by server applications authenticating themselves to a protected resource. 

I strongly recommend that commercetools implement an appropriate authentication flow for public client applications. The current recommendation is the Authorisation Code Flow with PKCE (ref: https://auth0.com/docs/get-started/authentication-and-authorization-flow/which-oauth-2-0-flow-should-i-use).

**Comment by ajimae** [comment]
Hi @mikehans 

The SDK is not recommended to be used on it own, it should be integrated into an application that is already managing environment/secrets properly.

Some suggestion is to use the SDK behind a proxy, a server or a frontend reading its data of being served by a server.

Using the SDK on a plain javascript build is not recommended.

**Comment by mikehans** [comment]
Hi @ajimae 
I'm glad to hear you say that. However, you have frontend examples that do exactly this.
