### ISSUE TITLE
MyLineItemDraft doesn't allow Selection By Sku

### ISSUE THREAD

**Issue by AlexW-Valtech** [commercetools/commercetools-sdk-typescript#46]
The spec for `MyLineItemDraft` allows for product selection to be done using either ids **or** sku - https://docs.commercetools.com/api/projects/me-carts#mylineitemdraft

However the type for `MyLineItemDraft` has `productId` and `variantId` as required, so you have to provide them:

```ts
export interface MyLineItemDraft {
  readonly productId: string
  readonly variantId: number

  /* ... other properties omitted ... */

  readonly sku?: string
}
```

I would expect this to be the same as `LineItemDraft`, which does have them as optional:

```ts
export interface LineItemDraft {

  readonly productId?: string
  readonly variantId?: number
  readonly sku?: string

  /* ... other properties omitted ... */
}
```

Is there a reason for this? Are we currently able to do Selection By Sku for `MyCartDraft`?

**Comment by jenschude** [comment]
Should be fixed with 1.11.0

Thanks for the report
