### ISSUE TITLE
Missing discountedPrice field in LineItem type

### ISSUE THREAD

**Issue by jletviniuk** [commercetools/commercetools-sdk-typescript#472]
Hi! i've notice that the discountedPrice field its not present in the cart lineItem type and in the documentation neither https://docs.commercetools.com/api/projects/carts#lineitem
I've fixed that, to access to it, extending the LineItem interface adding that field:
```
export interface LineItemWithDiscounts extends LineItem {
  discountedPrice?: DiscountedLineItemPrice;
}
```
but it would be nice if you can add that in a future update.
Thanks!

**Comment by jenschude** [comment]
It's a deprecated field and only present in the json for backwards compatibility reasons.
