### ISSUE TITLE
client.process fails with "expand: Invalid path selector"

### ISSUE THREAD

**Issue by danielseider** [commercetools/commercetools-sdk-typescript#513]
Request:
`const request = api
  .categories()
  .get({
    queryArgs: {
      limit: 500,
      withTotal: false,
      expand: ['parent', 'ancestors[*]'],
    },
  })
  .clientRequest();`
  
  `client.process(request, ....)` fails with message "Malformed parameter: expand: Invalid path selector: parent,ancestors[*]"}]},"name":"BadRequest"},"message":"Malformed parameter: expand: Invalid path selector: parent,ancestors[*]"
  
  i think this bug was introduced in #453
  v2.1.5 is working fine.

**Comment by ajimae** [comment]
Hi @danielseider 

Thanks for reporting this, we will look into it.

**Comment by ajimae** [comment]
This has been fixed in this [PR](https://github.com/commercetools/commercetools-sdk-typescript/pull/671)
