### ISSUE TITLE
'@commercetools/sync-actions' is missing type definitions

### ISSUE THREAD

**Issue by holzerch** [commercetools/commercetools-sdk-typescript#530]
It looks like the package `@commercetools/sync-actions` is missing type definitions which makes it hard to use with TypeScript

**Comment by ajimae** [comment]
Hi @holzerch 

Thanks for reporting this issue. Please, kindly open this issue [here instead](https://github.com/commercetools/nodejs/issues)


Thanks

**Comment by holzerch** [comment]
thanks @ajimae I opened it there https://github.com/commercetools/nodejs/issues/1884

**Comment by ajimae** [comment]
This issue was opened in the relevant repo.
