### ISSUE TITLE
typescript-sdk removal notice in readme?

### ISSUE THREAD

**Issue by mariuszkos** [commercetools/commercetools-sdk-typescript#56]
We're trying to use the SDK, but the notice in the npm package readme (https://www.npmjs.com/package/@commercetools/typescript-sdk) says the following:
```
Typescript SDK is moved to a new repository now, this package will be deleted soon from the current repository.
```
We depend on this package being available in NPM. Can you clarify when and why this package is destined to be removed from NPM?

**Comment by jenschude** [comment]
The typescript SDK was part of another repository and only included the parts for the platform API (https://api.<region>.commercetools.com)

When we moved the source to a separate repository the package had been renamed to `@commercetools/platform-sdk`

So it should be a drop in replacement to change your dependency from `typescript-sdk` to `platform-sdk`

**Comment by jenschude** [comment]
Please see also https://github.com/commercetools/nodejs/pull/1631/files

**Comment by jenschude** [comment]
I just saw that there was one version missing the deprecation notice at npm and updated it to avoid further confusion.

**Comment by mariuszkos** [comment]
Thank you for clarifying that.
