### ISSUE TITLE
Importing dependency breaks build system

### ISSUE THREAD

**Issue by MarkWissinkTekton** [commercetools/commercetools-sdk-typescript#560]
[This recent change](https://github.com/commercetools/commercetools-sdk-typescript/pull/545/files#diff-d872113c6f6834ae35f3dad0619e41a43455cf44654d0a56c774233f86bc5b4aR201) directly imports the `@commercetools/ts-sdk-apm` package using the `require` statement. Since`@commercetools/ts-sdk-apm` isn't a dependency of `@commercetools/sdk-client-v2`, it means the imported file might not exist at build time or runtime.

Currently this breaks our build process with Netlify functions where the build system includes statically referenced files. From [Netlify docs](https://docs.netlify.com/configure-builds/file-based-configuration/#functions):
> - included_files: list of additional paths to include in the function bundle. Although our build system includes statically referenced files (like require("./some-file.js")) 

I'm not sure what the best resolution is here, but I don't think directly importing files from the `@commercetools/ts-sdk-apm` is ideal. A current workaround for our build step is to install `@commercetools/ts-sdk-apm` in our project, but I don't think that's a good, long-term solution

**Comment by jenschude** [comment]
Yes! Definitely not intended. We will soon release a fix for this.

**Comment by jenschude** [comment]
We just released a patched version which for now omits the package version in the UserAgent string.

This should solve the immediate issue. We'll look into a solution how to retrieve the version number without the implicit dependency

**Comment by MarkWissinkTekton** [comment]
Awesome, thanks for the quick update!
