### ISSUE TITLE
'@commercetools/platform-sdk' missing type for `RangeFacetResult`

### ISSUE THREAD

**Issue by Rtwena** [commercetools/commercetools-sdk-typescript#567]
https://github.com/commercetools/commercetools-sdk-typescript/blob/38f7aef3496cca0a079d05fa5ba1daf85a887634/packages/platform-sdk/src/generated/models/product.ts#L994-L999

`dataType` is missing from `RangeFacetResult` 

according to the docs it could be many types https://docs.commercetools.com/api/projects/products-search#rangefacetexpression

and in http api response we get back `dataType`
```json
{
            "type": "range",
            "dataType": "number",
            "ranges": [
                {
                    "type": "double",
                    "from": 0.0,
                    "fromStr": "0.0",
                    "to": 0.0,
                    "toStr": "",
                    "count": 4,
                    "totalCount": 4,
                    "total": 8143.0,
                    "min": 2007.0,
                    "max": 2052.0,
                    "mean": 2035.75
                }
            ]
        }
```

**Comment by jenschude** [comment]
It's missing cause it's not an officially documented field

https://docs.commercetools.com/api/projects/products-search#rangefacetresult

Please see also:

https://docs.commercetools.com/api/general-concepts#json

```
In addition, client applications should not rely on the presence of undocumented fields. Fields returned by an undocumented endpoint can be renamed or removed at any time without prior notice.
```

**Comment by Rtwena** [comment]
okay, thanks
