### ISSUE TITLE
Sorting by name does not work in Product Projections

### ISSUE THREAD

**Issue by IgnacioNMiranda** [commercetools/commercetools-sdk-typescript#568]
Going through the [documentation](https://docs.commercetools.com/api/projects/productProjections#query-productprojections) I understand we're able to [sort the results of product projections using the `name` attribute](https://docs.commercetools.com/api/general-concepts#sorting) when using the following api:
```
await client
      .productProjections()
      .get({
        queryArgs: {
          sort: 'name asc'
        },
      })
      .execute();
```

However, when calling this, we get the following error: `Malformed parameter: sort: Invalid query field 'name' in sort path. Sortable fields are: ``.` but the documentation said **name** is a valid field to be sorted, we even have the `name asc` example [here](https://docs.commercetools.com/api/general-concepts#sorting). I would expect to get a successful response with the results being sorted by name in ascending order.

Node: [e.g. 18]
@commercelayer/sdk: [5.16.0]
@commercetools/platform-sdk: [7.0.0]

**Comment by jenschude** [comment]
The documentation about sorting is generalized.

In the product projection the field `name` is of type LocalizedString. So you would have to add the locale too. For example `en` for english:

```
name.en asc
```

**Comment by IgnacioNMiranda** [comment]
Thanks @jenschude funny enough I was just testing and tried exactly that and it worked xD.
Maybe I'm too silly but I'd say the documentation should be more explicit about it as the name is a really common field to be sorted

**Comment by jenschude** [comment]
But not all names are of type LocalizedString. But yeah it may be necessary to use a field which produces less confusion
