### ISSUE TITLE
Strange import in sdk-client-v3 makes it impossible to build with Bun

### ISSUE THREAD

**Issue by rasmusbe** [commercetools/commercetools-sdk-typescript#584]
This import makes the build fail when I build into a project using the [Bun](https://bun.sh/) bundler and it seems to be an incorrect import

https://github.com/commercetools/commercetools-sdk-typescript/blob/078a76ec4cfbe7a768e1f6096ee085eb6cbbf5c7/packages/sdk-client-v3/src/middleware/create-http-middleware.ts#L2

**Comment by ajimae** [comment]
Hi @rasmusbe 

Can I see your bun `build.{js|ts}` file or how you are carrying out the build, I would like to see if I can reproduce it. 

Also, you paste the error stack here as well.

Thanks

**Comment by ajimae** [comment]
I just tried and I was able to build and bundle all the packages within the workspace into a `dist` directory using the snippet below

```js
// build.js
await Bun.build({
  outdir: './dist',
  entrypoints: [
    './packages/history-sdk/src/index.ts',
    './packages/importapi-sdk/src/index.ts',
    './packages/ml-sdk/src/index.ts',
    './packages/platform-sdk/src/index.ts',
    './packages/sdk-client/src/index.ts',
    './packages/sdk-client-v3/src/index.ts'
  ],
});
```

**Comment by rasmusbe** [comment]
Never mind, seems to have been something corrupt with my node_modules, it seems to be working now
