### ISSUE TITLE
How to handle tokens in a Next.js app

### ISSUE THREAD

**Issue by claudiulazar** [commercetools/commercetools-sdk-typescript#606]
I have took a look upon the documentation and tutorials.
I didn't manage to find a best practice way to use this SDK in an Next.js app.

Issue: How can you sent to the Client Side a token if you can not get it? I couldn't find anything regarding the retrieval of the token in the documentation. This means that for every logged in user I need either to get the token by making direct request to the oauth endpoints and then send it to the client side the token and refreshToken or send everytime the email and password which is a no go.

Can somebody please suggest how should this be handled? I want to use the SDK only on SSR and not give any info to the client side except the token they use.

**Comment by ajimae** [comment]
Hi @claudiulazar,

There are different way this can be achieved.

- You can take a look at this [issue](https://github.com/commercetools/commercetools-sdk-typescript/issues/314) specifically this [package](https://www.npmjs.com/package/@commercetools/sdk-auth) from us, the docs can also be found [here](https://commercetools.github.io/nodejs/sdk/api/sdkAuth.html)

- You can pass in a callback into the fetch function to retried the access_token and use it wherever you want.

```ts
...
const fetch = require('node-fetch');

const cb = (token) => {
   console.log(token);
}

async function fetcher(...args) {
  const r = await fetch(...args),
        const t = r.clone(),
        const tt = await t.json(); // tt will hold value of the token which can be accessed.

  cb(tt.body.access_token);
  return r;
}
...
```

Then in your `withAnonymousSessionFlow` or whichever auth flow you are using, you can do this:

```ts
const anonClient = new ClientBuilder()
  ...
  .withAnonymousSessionFlow({
    ...
   fetch: fetcher
  }).build();
```

**Comment by claudiulazar** [comment]
Hi @ajimae thank you for your fast reply.

First option: I would avoid the first option because I could not find a reference to this package only by going to the "previous" SDK. At least in my head is that this will be deprecated sometime.

Second option: It works, only one thing, it's not `tt.body.access_token` it's directly `tt.access_token`.
And indeed this is a way of passing the token but it seems a little bit "hackish" by wrapping the fetch function. I think I will go with this option.

Would be nice to have a reference in the official documentation regarding how to get a token. 

I will close this issue for now.
