### ISSUE TITLE
discountOnTotalPrice property not returned in GET /orders response

### ISSUE THREAD

**Issue by lejlabe** [commercetools/commercetools-sdk-typescript#609]
version: **@commercetools/platform-sdk@7.3.0**

Order has got discountOnTotalPrice applied and its value is returned in the API response. When using the SDK, discountOnTotalPrice is undefined for the Order.

**Comment by ajimae** [comment]
@lejlabe 

Please can you share code snippets on what you are doing and how you also made the direct api call.

Thanks

**Comment by lejlabe** [comment]
hi @ajimae 
I've tried this morning and could not reproduce the issue. 
This is the code snippet
```
  async fetchOrders(orderIds: string[], commerceConfig: ICommerceConfig): Promise<Order[]> {
    const orderIdsQuery: string = _.map(orderIds, id => `"${id}"`).join(', ');
    try {
      return (
        await this.apiRoot
          .withProjectKey({ projectKey: commerceConfig.commerceProjectName })
          .orders()
          .get({
            queryArgs: {
              where: `id in (${orderIdsQuery})`,
              expand: [
                'customerGroup',
                'lineItems[*].price.discounted.discount',
                'paymentInfo.payments[*]',
                'shippingInfo.shippingMethod',
                'state',
              ]
            },
          })
          .execute()
      ).body.results;
    } catch (error) {
      throw new Error(`Fetch orders failed with ${error.statusCode}: ${error.body}`);
    }
  }
```

I will close the issue for now, and will reopen it in case it happens again. Thank you.

**Comment by lejlabe** [comment]
Hi @ajimae! Unfortunately I am able to reproduce the issue again.

With @commercetools/platform-sdk@7.3.0, this is a code snipped used to fetch orders
```
  async fetchOrders(orderIds: string[], commerceConfig: ICommerceConfig): Promise<Order[]> {
    const orderIdsQuery: string = _.map(orderIds, id => `"${id}"`).join(', ');
    try {
      return (
        await this.apiRoot
          .withProjectKey({ projectKey: commerceConfig.commerceProjectName })
          .orders()
          .get({
            queryArgs: {
              where: `id in (${orderIdsQuery})`,
              expand: [
                'customerGroup',
                'lineItems[*].price.discounted.discount',
                'paymentInfo.payments[*]',
                'shippingInfo.shippingMethod',
                'state',
              ]
            },
          })
          .execute()
      ).body.results;
    } catch (error) {
      throw new Error(`Fetch orders failed with ${error.statusCode}: ${error.body}`);
    }
  }
```

In the response, there is no `discountOnTotalPrice` property for the order. 
With direct API call, it is returned as expected:
![Uploading Screenshot 2024-02-22 at 08.13.11.png…]()

**Comment by jenschude** [comment]
The SDK doesn't has any influence on the presence of the field. The field itself is optional, so it's not guaranteed to be existing and you have to check for it.

From the documentation it says that it's only present if there was a total price cart discount applied.

**Comment by jenschude** [comment]
Yes it is. But did you ensured that you try to access this particular resource? I can see that you did a query for multiple orders. Do all of them have the field set?
