### ISSUE TITLE
Incomplete type information on product availability

### ISSUE THREAD

**Issue by ghost** [commercetools/commercetools-sdk-typescript#625]
The [type definition](https://github.com/commercetools/commercetools-sdk-typescript/blob/77f2d249208729ba0a9151720a66f65e762b34ec/packages/platform-sdk/src/generated/models/product.ts#L887) for `ProductVariantAvailability` appears to be incomplete because the response from the API includes the ID and version of the associated inventory entry. 

It seems like definition for `ProductVariantAvailability` should be a superset of `ProductVariantChannelAvailability` with the addition of the `channels` map. This would be helpful since an inventory entry could be immediately updated given a product, rather than having to fetch the inventory entry for each variant.

**Comment by MarkWissinkTekton** [comment]
@jenschude I realized that I forgot to mention our products are using an inventory entry without a channel. This means the resulting availability for a product looks like the following:
```
"availability": {
  "isOnStock": true,
  "availableQuantity": 20,
  "version": 1,
  "id": "f64af276-a1ad-4eea-a8bc-89c453742a40"
}
```

**Comment by MarkWissinkTekton** [comment]
I also found that the ID and version are included in the [Commercetools documentation](https://docs.commercetools.com/api/projects/products#productvariantavailability) for `ProductVariantAvailability`

**Comment by jenschude** [comment]
Yes. It has been added today. The changes are already merged to this repository. Both fields will be available with the next release.

Please see also: https://github.com/commercetools/commercetools-sdk-typescript/pull/626/files

**Comment by MarkWissinkTekton** [comment]
Awesome, thanks!

**Comment by ajimae** [comment]
Closing this as completed. 🥂
