### ISSUE TITLE
Custom logger function always receives undefined response

### ISSUE THREAD

**Issue by fhaertig** [commercetools/commercetools-sdk-typescript#653]
When we use a custom logger middleware on our client, the response it logs always contains undefined for every value.

We're setting up a client like this:

```
{
const client = new ClientBuilder()
  .withProjectKey(<commercetoolsProjectKey>)
  .withClientCredentialsFlow(authMiddlewareOptions)
  .withHttpMiddleware(httpMiddlewareOptions)
  .withUserAgentMiddleware(...)
  .withMiddleware(this.loggerMiddleware())
  .build();


const apiRoot = createApiBuilderFromCtpClient(client);
}

private loggerMiddleware(): Middleware {
        return function (next) {
            return function (request, response) {
                const { body, statusCode } = response;
                   //LOG response
           }
      }
}

```

The logs we see show the request details correctly, but it always logs the same thing for the response:

`Response:  { error: undefined, body: undefined, statusCode: undefined }`

The issue already existed about 2 years ago: https://github.com/commercetools/commercetools-sdk-typescript/issues/326

versions we use:
"@commercetools/platform-sdk": "^7.5.0"
"@commercetools/sdk-client-v2": "^2.4.0"

**Comment by ajimae** [comment]
This has been fixed in this [PR](https://github.com/commercetools/commercetools-sdk-typescript/pull/676). You can update to the latest versioin [@commercetools/sdk-client-v2@2.5.0](https://www.npmjs.com/package/@commercetools/sdk-client-v2)

Thanks
