### ISSUE TITLE
Incorrect type for `address` property on `CustomerChangeAddressAction`

### ISSUE THREAD

**Issue by jimmythomson** [commercetools/commercetools-sdk-typescript#71]
The `address` property is defined as a `BaseAddress` type on the `CustomerChangeAddressAction` interface. I believe that it should be `AddressDraft` (as per the REST API docs):

https://github.com/commercetools/commercetools-sdk-typescript/blob/master/packages/platform-sdk/src/generated/models/customer.ts#L577

https://docs.commercetools.com/api/projects/me-profile#change-address

I think the same issue applies to the `CustomerAddAddressAction` too.

Thanks

**Comment by jenschude** [comment]
It has been defined as BaseAddress for backwards compatibility. Address as well as AddressDraft inherit from BaseAddress

**Comment by jenschude** [comment]
Also it allows to directly use an Address for an update action without creating an AddressDraft first.

And please keep in mind the reference is also used for other languages without structural typing

**Comment by jenschude** [comment]
Thought about this too already. But has to be changed in the generator as like as it had been done for the update actions itself.

**Comment by jimmythomson** [comment]
Okay. I'm not familiar with the generator, so if it's not possible we'll cast it for now :) Thanks.
