### ISSUE TITLE
Are there any plans to support the new product search on the SDK?

### ISSUE THREAD

**Issue by matiasgarcia91** [commercetools/commercetools-sdk-typescript#713]
There's a new product search endpoint out for public Beta [docs](https://docs.commercetools.com/api/releases/2024-03-26-introduced-product-search-in-beta). Are there any plans to support this new search through the SDK? 
Thanks for your time!

**Comment by jenschude** [comment]
Supported since 7.6 https://github.com/commercetools/commercetools-sdk-typescript/releases/tag/%40commercetools/platform-sdk%407.6.0

**Comment by matiasgarcia91** [comment]
Great! thanks for the answer
