### ISSUE TITLE
The browser.html example doesn't work with producing a CORS error

### ISSUE THREAD

**Issue by MurzNN** [commercetools/commercetools-sdk-typescript#743]
**Describe the bug**
I'm trying to make the basic browser example from [browser.html](https://github.com/commercetools/commercetools-sdk-typescript/blob/6982a15ab478797364cf338d8dcaea5def907259/examples/browser/browser.html) work well, but it can't load the data from the API endpoint, giving the CORS error:
```
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://auth.us-central1.commercetools.com/oauth/token. (Reason: CORS request did not succeed). Status code: (null).
```

**To Reproduce**
1. Copy-paste the `browser.html` from the example.
2. Fill the urls and credentials.
3. Open this file in a browser.
4. See the "CORS request did not succeed" error.

**Expected behavior**
The example should work out of the box, without additional actions to manage CORS issues.

**Stack information (please complete the following information):**

- Node: Firefox browser
- SDK: 7.9.0

**Comment by ajimae** [comment]
Hi @MurzNN,

This should work as expected once #751 is merged.

Thanks
