### ISSUE TITLE
active attribute is missing from ShippingMethod and ShippingMethodDraft

### ISSUE THREAD

**Issue by e1d0** [commercetools/commercetools-sdk-typescript#759]
**Describe the bug**
`ShippingMethod` and `ShippingMethodDraft` is missing `active` attribute

### exampling of adding a manual syncing of the shipping methods from Project A -> Project B

<img width="1355" alt="image" src="https://github.com/user-attachments/assets/c55bd81a-ec22-4c43-b649-d150bf23c58f">

**To Reproduce**
- When adding a new shipping method using the SDK, and add the `active` field.
- When querying shipping method using the SDK, `active` is not found.

**Expected behavior**
expect to have the type match the API response.

![CleanShot 2024-07-24 at 14 20 52](https://github.com/user-attachments/assets/471cd58e-3f9b-41d9-bb5a-90a7baeca993)

**Screenshots/Code snippet**
attached above
**Stack information (please complete the following information):**

- Node: [v20.10.0]
- SDK: [7.8.0 and and 7.10.0-alpha-customer-groups.2]

**Additional context**
N/A

**Comment by ajimae** [comment]
Hi @e1d0 

I will be closing this issue, please feel free to reopen if issue still persists.

Thanks

**Comment by suexpert** [comment]
thanks @ajimae  <3
