### ISSUE TITLE
Typescript Platform SDK: Issue with CartSetCustomerEmailAction on Me-Endpoint

### ISSUE THREAD

**Issue by ashishhk** [commercetools/commercetools-sdk-typescript#81]
https://jira.commercetools.com/browse/SUPPORT-12615

**Comment by MicheleRezk** [comment]
Created [PR](https://github.com/commercetools/commercetools-docs/pull/1158) to include missing Raml type of MyCartSetCustomerEmailAction

**Comment by MicheleRezk** [comment]
it's solved in the new release [1.15.0](https://www.npmjs.com/package/@commercetools/platform-sdk) version of the SDK
